### ISSUE TITLE
Add a Navbar 

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#1]

**Comment by ST1LLWATER** [comment]
I req to contrib to this issue

**Comment by rohan26062001** [comment]
> /assign

Please assign me

**Comment by mifrasgaffoor** [comment]
Hey @Buddhad  i am searching for projects and issues for my very first hacktoberfest contributions .... can you please assign it to me .
Thanks in advance!

**Comment by pragyachhabra01** [comment]
hey @Buddhad 
Kindly assign this issue to me
