### ISSUE TITLE
Add Pages 

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#15]

**Comment by Sugam50** [comment]
Hi , I would like to work on this issue . Assign me on this issue

**Comment by meixinchoy** [comment]
Hello :) I would love to work on this issue by creating an "About" page that provides information about what Hacktoberfest is all about.

**Comment by Buddhad** [comment]
> Hello :) I would love to work on this issue by creating an "About" page that provides information about what Hacktoberfest is all about.

Okay

**Comment by yadavashishdhirendra** [comment]
Hey @Buddhad , I would like to work on creating new pages, can u assign it to me!

**Comment by Buddhad** [comment]
> Hey @Buddhad , I would like to work on creating new pages, can u assign it to me!

Others are working on that section.

**Comment by Buddhad** [comment]
> Hey @Buddhad , I would like to work on creating new pages, can u assign it to me!

Create a `Home` page section.
