### ISSUE TITLE
Add a Splash Screen 

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#23]

**Comment by shreya024** [comment]
@Buddhad I would like to work on this issue...Kindly assign me this

**Comment by sumitkumarju** [comment]
@Buddhad  Can you please elaborate a bit

**Comment by Buddhad** [comment]
So you need to add a splash screen when the website going to open the first thing that is visible is the splash screen(like a logo).
- Use a Gif for Splash screen.
