### ISSUE TITLE
Add a Dark Mode

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#25]
You should add a dark mode switch button that, when clicked, changes the mode

**Comment by CLOEI** [comment]
Hello, may i be assigned to do it?, and where should i put the switch button?

**Comment by RajaVardhan-coder** [comment]
I want to work on this issue. Please assign me.

**Comment by Buddhad** [comment]
> Hello, may I be assigned to do it?, and where should I put the switch button?
You should add a Darkmode botton in the header section.

**Comment by iqbalutomo** [comment]
As per my previous promise, I want to work on this issue. Please assign me🙏🏼
