### ISSUE TITLE
Add your ProfileCard 

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#31]
## Things you Need to Follow
- You just need to add your name 
- Github Link 
- add a photo 
- Add a short bio

**Comment by P-riyanka-prasad** [comment]
I am going to add my profile card.

**Comment by artiyadav28** [comment]
I am adding my profile card

**Comment by Juan-Gon03** [comment]
Just added my profile card.😁

**Comment by SoundaryaKhanapur** [comment]
Okay, i'll add my profile card :)

**Comment by TheInspiredConjurer** [comment]
I'll also add my profile card

**Comment by yashikajotwani12** [comment]
I'll also add my profile card.

**Comment by pritambera2000** [comment]
I'm adding my profile card

**Comment by N-Deepika** [comment]
I'm adding my profile card.

**Comment by kastrahl** [comment]
will add mine if u dont mind

**Comment by homewardgamer** [comment]
I will be happy to add mine too!!1

**Comment by artiyadav28** [comment]
adding my profile card

**Comment by anjali-yadav** [comment]
adding my profile card

**Comment by Yashvi30** [comment]
I'll add my profile card :)

**Comment by Athul0491** [comment]
i'll add my profile card as well!
