### ISSUE TITLE
Add a header 

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#4]
## Need to be there
- In header section `Home` `Contribution`  `About` `Contact Us`

**Comment by TheInspiredConjurer** [comment]
Hello. I'm new to open-source.

Can I contribute to this, please?

**Comment by Buddhad** [comment]
@TheInspiredConjurer  Hey, can you work on the  issue #5

**Comment by TheInspiredConjurer** [comment]
I would love to!

Thanks for giving me the chance!
