### ISSUE TITLE
Fixed the Footer In Mobile View

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#45]
- Need to fix the bug in the **Mobile view**

**Comment by shiv0403** [comment]
@Buddhad can you assign this issue to me?

**Comment by Shubh-2402** [comment]
HEY @Buddhad  , I would like to work on this issue . Can you please elaborate the issue in detail?

**Comment by Buddhad** [comment]
# Need to fix the Footer section 
- In the Mobile View 
![bug](https://cdn.discordapp.com/attachments/844987912311406633/894071751250706472/Screenshot_2021-10-03-09-31-44-77.jpg)

@Shubh-2402

**Comment by Shubh-2402** [comment]
copyright should be below the social-media links right?

**Comment by Buddhad** [comment]
> copyright should be below the social-media links right?

Yeah,The logos need to be shifted right.

**Comment by Shubh-2402** [comment]
I've have fixed the issue ,please check my PR #50 and accept the pull request
