### ISSUE TITLE
Add Background and Animations

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/Contribution_Website#5]
## Important 
- Hover animations 
- Background you added matches with the **Color** and **design**
- Card Animations

**Comment by ayasahmad63** [comment]
I am working on it

**Comment by Buddhad** [comment]
Okay

**Comment by shutupRohit** [comment]
hey ! can i work on this issue ?

**Comment by Buddhad** [comment]
Yeah, you can work on this issue. @shutupRohit

**Comment by shutupRohit** [comment]
@Buddhad can u please assign me this issue.

**Comment by shutupRohit** [comment]
is this hover effect good ?
![Effect1](https://user-images.githubusercontent.com/78253058/135742299-d60d0bf0-c1db-4aa3-a94a-c79512e002a9.png)


- Box shadow
- Animated name underline

**Comment by Buddhad** [comment]
Wow, that looks really good.
- Just center the image and you're good to go.
@shutupRohit

**Comment by Buddhad** [comment]
Could you please add hover effects to the *Navbar* I would really appreciate it?

**Comment by sumitkumarju** [comment]
Hey @Buddhad I can add that.Can you assign it to me?

> Could you please add hover effects to the _Navbar_ I would really appreciate it?

**Comment by shutupRohit** [comment]
@Buddhad  sure

**Comment by Buddhad** [comment]
I am so **impressed** with your work @sumitkumarju .

**Comment by sumitkumarju** [comment]
> I am so **impressed** with your work @sumitkumarju .

Thanks @Buddhad .What should i work on now?

**Comment by Buddhad** [comment]
@sumitkumarju You can work on this  #23  issue.
