### ISSUE TITLE
fix navigation bar 

### ISSUE THREAD

**Issue by meixinchoy** [Buddhad/Contribution_Website#57]
Hi, I would like to work on the navigation bar by fixing it on top and making sure that nothing covers it

![image](https://user-images.githubusercontent.com/65379600/135748579-5b8cd6e7-ac51-4485-92c4-a1ea7d8505cb.png)

**Comment by Buddhad** [comment]
I would **appreciate** your assistance with this matter .

**Comment by Buddhad** [comment]
## Need to fix this 
- The last contributor's description isn't visible when the mobile view is open.
![image](https://user-images.githubusercontent.com/71445997/135749706-1dcbc5af-6d0e-49de-80bd-495dd6bb0460.png)

**Comment by Buddhad** [comment]
> Hi, I would like to work on the navigation bar by fixing it on top and making sure that nothing covers it
> 
> ![image](https://user-images.githubusercontent.com/65379600/135748579-5b8cd6e7-ac51-4485-92c4-a1ea7d8505cb.png)

## There is some bugs in your contribution image is stick in the header section and not able to be visible  @meixinchoy .

![image](https://user-images.githubusercontent.com/71445997/135750103-0cb4ddbf-9b38-42ef-a239-5dd6a72dda75.png)

**Comment by Buddhad** [comment]
Thanks for your contribution, the problem has been resolved.
