### ISSUE TITLE
fix: Landing page is cropped

### ISSUE THREAD

**Issue by vedant-jain03** [Buddhad/Contribution_Website#63]
![Screenshot (150)](https://user-images.githubusercontent.com/76901313/135750187-cd0f4c65-877b-4f01-93e4-458a96323b4d.png)

Landing page is not fully visible.

**Comment by vedant-jain03** [comment]
@Buddhad  would you mind tagging this issue with hacktoberfest and assigning this to me?

**Comment by Buddhad** [comment]
## Need to fix this issue 
- Content in the `upper header` is not visible
![image](https://user-images.githubusercontent.com/71445997/135750594-5e5e66dd-ed68-40d4-91af-c9cc05991676.png)
