### ISSUE TITLE
fix: About Us Text color is not appropriate

### ISSUE THREAD

**Issue by vedant-jain03** [Buddhad/Contribution_Website#66]
Before:
![Screenshot (151)](https://user-images.githubusercontent.com/76901313/135750958-83488eb8-72fd-44ef-b92a-3f89584d75e6.png)

After:
![Screenshot (152)](https://user-images.githubusercontent.com/76901313/135750984-c1d2265f-1251-41a3-8b5e-d12637017ee5.png)

**Comment by vedant-jain03** [comment]
@Buddhad

**Comment by Buddhad** [comment]
Yeah you can work on this issue

**Comment by Buddhad** [comment]
but I guess you are in the dark mode that's why it looks like this.

**Comment by vedant-jain03** [comment]
> but I guess you are in the dark mode that's why it looks like this.
But that also looking odd.

**Comment by Buddhad** [comment]
Okay thanks for the help you can also PR in here  #31

**Comment by Buddhad** [comment]
@vedant-jain03 can you add a `switch button` of Dark mode to light cuz it's your previous contribution is not compatible with light mode.

**Comment by Buddhad** [comment]
- if you are not able to do that I have to `revert` the code cuz the text are not visible.
![image](https://user-images.githubusercontent.com/71445997/135751697-07b0add1-7da4-4d0b-b6fd-39bf6318eb2f.png)
